export const ironBrotherAbi = [
  {
    type: 'event',
    name: 'UserRegistered',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'referrer', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'UserIndexed',
    inputs: [{ name: 'user', type: 'address', indexed: true }],
  },
  {
    type: 'event',
    name: 'DefaultReferrerUpdated',
    inputs: [{ name: 'defaultReferrer', type: 'address', indexed: true }],
  },
  {
    type: 'event',
    name: 'OwnerTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true },
      { name: 'newOwner', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'Deposited',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'orderId', type: 'uint256', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DepositRouted',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'receiverIndex', type: 'uint8', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DepositReceiversUpdated',
    inputs: [{ name: 'receivers', type: 'address[5]', indexed: false }],
  },
  {
    type: 'event',
    name: 'PrincipalRedeemed',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'orderId', type: 'uint256', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Reinvested',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'orderId', type: 'uint256', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'StakeCreated',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'stakeId', type: 'uint256', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'reward', type: 'uint256', indexed: false },
      { name: 'day', type: 'uint256', indexed: false },
      { name: 'session', type: 'uint8', indexed: false },
      { name: 'settleAt', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'StakeSettled',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'stakeId', type: 'uint256', indexed: true },
      { name: 'principal', type: 'uint256', indexed: false },
      { name: 'reward', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DynamicRewardSettled',
    inputs: [
      { name: 'source', type: 'address', indexed: true },
      { name: 'upline', type: 'address', indexed: true },
      { name: 'day', type: 'uint256', indexed: false },
      { name: 'generation', type: 'uint8', indexed: false },
      { name: 'volume', type: 'uint256', indexed: false },
      { name: 'reward', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DynamicRewardBotSettled',
    inputs: [
      { name: 'operator', type: 'address', indexed: true },
      { name: 'day', type: 'uint256', indexed: true },
      { name: 'cursor', type: 'uint256', indexed: false },
      { name: 'processed', type: 'uint256', indexed: false },
      { name: 'rewardedUsers', type: 'uint256', indexed: false },
      { name: 'totalReward', type: 'uint256', indexed: false },
      { name: 'nextCursor', type: 'uint256', indexed: false },
      { name: 'finished', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'WithdrawalRequested',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'fee', type: 'uint256', indexed: false },
      { name: 'netAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'WithdrawalApproved',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'payer', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'fee', type: 'uint256', indexed: false },
      { name: 'netAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'WithdrawalRejected',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'requestId', type: 'uint256', indexed: true },
      { name: 'operator', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RewardsFunded',
    inputs: [
      { name: 'funder', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ContractFundsWithdrawn',
    inputs: [
      { name: 'operator', type: 'address', indexed: true },
      { name: 'receiver', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Whitelist40Updated',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'enabled', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'DEFAULT_ADMIN_ROLE',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'MANAGER_ROLE',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'DEPOSIT_RECEIVER_COUNT',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'MAX_BOT_SETTLEMENT_BATCH',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'users',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [
      { name: 'referrer', type: 'address' },
      { name: 'principalBalance', type: 'uint256' },
      { name: 'principalStaked', type: 'uint256' },
      { name: 'rewardBalance', type: 'uint256' },
      { name: 'totalDeposited', type: 'uint256' },
      { name: 'totalStaked', type: 'uint256' },
      { name: 'totalStaticReward', type: 'uint256' },
      { name: 'totalDynamicReward', type: 'uint256' },
      { name: 'totalWithdrawn', type: 'uint256' },
      { name: 'directCount', type: 'uint256' },
      { name: 'registered', type: 'bool' },
      { name: 'whitelist40', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'availablePrincipal',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maturedUnredeemedPrincipal',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'currentSession',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }, { type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'currentLocalDay',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'settlementCycle',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'eligibleGeneration',
    stateMutability: 'view',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'day', type: 'uint256' },
    ],
    outputs: [{ type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'generationRateBps',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint8' }],
    outputs: [{ type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'yieldBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'withdrawFee',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'withdrawalApprovalDisabled',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'withdrawalApprovalRequired',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'minAmount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxAmount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxPrincipal',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'lockPeriod',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'minYieldBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxYieldBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'validVolumeThreshold',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'paused',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'feeReceiver',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'defaultReferrer',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'timezoneOffset',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'int256' }],
  },
  {
    type: 'function',
    name: 'morningStart',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'morningEnd',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'afternoonStart',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'afternoonEnd',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'nextPrincipalOrderId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'nextStakeOrderId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'nextDepositReceiverIndex',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'nextWithdrawalRequestId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalUsers',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalDepositedAmount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalPrincipalBalance',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalRewardBalance',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalStakedVolume',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalStaticRewardCredited',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalDynamicRewardCredited',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalWithdrawnAmount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'totalPendingWithdrawalAmount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'dailyStakeVolume',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'address' },
      { name: '', type: 'uint256' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'isValidOnDay',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'address' },
      { name: '', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'dailyDirectValidCount',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'address' },
      { name: '', type: 'uint256' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'dynamicRewardSettled',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'address' },
      { name: '', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getDynamicRewardHistory',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [
      {
        type: 'tuple[]',
        components: [
          { name: 'source', type: 'address' },
          { name: 'day', type: 'uint256' },
          { name: 'generation', type: 'uint8' },
          { name: 'volume', type: 'uint256' },
          { name: 'reward', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'hasRole',
    stateMutability: 'view',
    inputs: [
      { name: 'role', type: 'bytes32' },
      { name: 'account', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getUserPrincipalOrderIds',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'getUserStakeOrderIds',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'getUserWithdrawalRequestIds',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'getDirectReferrals',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'getAllUsers',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'getDepositReceivers',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address[5]' }],
  },
  {
    type: 'function',
    name: 'principalOrders',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'user', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'unlockAt', type: 'uint256' },
      { name: 'source', type: 'uint8' },
      { name: 'status', type: 'uint8' },
    ],
  },
  {
    type: 'function',
    name: 'stakeOrders',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'user', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'rewardBps', type: 'uint256' },
      { name: 'reward', type: 'uint256' },
      { name: 'day', type: 'uint256' },
      { name: 'session', type: 'uint8' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'settleAt', type: 'uint256' },
      { name: 'settled', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'withdrawalRequests',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'user', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'fee', type: 'uint256' },
      { name: 'netAmount', type: 'uint256' },
      { name: 'requestedAt', type: 'uint256' },
      { name: 'processedAt', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'operator', type: 'address' },
      { name: 'payer', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'register',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'referrer', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'referrer', type: 'address' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'stake',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleStake',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'stakeId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleStakes',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'stakeIds', type: 'uint256[]' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'redeemPrincipal',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'orderId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'reinvest',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'requestWithdrawRewards',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'fundRewards',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdrawContractFunds',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'receiver', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'approveWithdrawal',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'requestId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'rejectWithdrawal',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'requestId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleDynamicRewardForUser',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'day', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleDynamicRewardForUsers',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'userList', type: 'address[]' },
      { name: 'day', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleDynamicRewardForSourceDays',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'userList', type: 'address[]' },
      { name: 'dayList', type: 'uint256[]' },
    ],
    outputs: [
      { name: 'processed', type: 'uint256' },
      { name: 'rewardedUsers', type: 'uint256' },
      { name: 'totalReward', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'botSettleDailyDynamicRewards',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'day', type: 'uint256' },
      { name: 'cursor', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'processed', type: 'uint256' },
      { name: 'rewardedUsers', type: 'uint256' },
      { name: 'totalReward', type: 'uint256' },
      { name: 'nextCursor', type: 'uint256' },
      { name: 'finished', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'syncRegisteredUsers',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'accountList', type: 'address[]' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setYieldBps',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newYieldBps', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setYieldBounds',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'newMinYieldBps', type: 'uint256' },
      { name: 'newMaxYieldBps', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setAmountRules',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'newMinAmount', type: 'uint256' },
      { name: 'newMaxAmount', type: 'uint256' },
      { name: 'newMaxPrincipal', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setLockPeriod',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newLockPeriod', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setPrincipalOrderLockPeriod',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'orderId', type: 'uint256' },
      { name: 'newLockPeriod', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setWithdrawFee',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newWithdrawFee', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setWithdrawalApprovalRequired',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'required', type: 'bool' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setFeeReceiver',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newFeeReceiver', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setDepositReceivers',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newDepositReceivers', type: 'address[5]' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setDefaultReferrer',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newDefaultReferrer', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setValidVolumeThreshold',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newThreshold', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setSettlementCycle',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newSettlementCycle', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setSessionTimes',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'newMorningStart', type: 'uint32' },
      { name: 'newMorningEnd', type: 'uint32' },
      { name: 'newAfternoonStart', type: 'uint32' },
      { name: 'newAfternoonEnd', type: 'uint32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setTimezoneOffset',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newTimezoneOffset', type: 'int256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setGenerationRate',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'generation', type: 'uint8' },
      { name: 'rateBps', type: 'uint16' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setWhitelist40',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'enabled', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setManager',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'enabled', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setAdmin',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'account', type: 'address' },
      { name: 'enabled', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'transferOwner',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newOwner', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unpause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
] as const;

export const erc20Abi = [
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
] as const;
